In [1]:
import sys
import numpy as np
import pandas as pd

import tensorflow as tf

In [2]:
print(sys.version)

3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]


In [62]:
arr = np.random.randint(10, size=10)

In [63]:
ds = tf.data.Dataset.from_tensor_slices(arr)

In [68]:
n = 0
for e in ds:
    n += e.numpy()
    print(e)
print(n)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
0


In [14]:
e.numpy()

1

In [26]:
type(iter(ds))

tensorflow.python.data.ops.iterator_ops.OwnedIterator

In [27]:
type(ds)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [51]:
ds2 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4,10]))

print("- - - - - - - - ds2 - - - - - - - -")
print(tf.random.uniform([4,10]))
ds3 =(tf.random.uniform([4]),
      tf.random.uniform([4, 4], maxval=100, dtype=tf.int32))

print("- - - - - - - - ds3 - - - - - - - -")
print(ds3)
ds3 = tf.data.Dataset.from_tensor_slices(ds3)

- - - - - - - - ds2 - - - - - - - -
tf.Tensor(
[[0.47324824 0.5358292  0.68424356 0.6670543  0.39903927 0.74895215
  0.02241492 0.7940999  0.96831155 0.3296466 ]
 [0.90393615 0.21639478 0.00346696 0.00973201 0.59110105 0.6534457
  0.34532034 0.44684315 0.7754146  0.75971067]
 [0.05918646 0.92768335 0.08951044 0.5959326  0.1223489  0.64387894
  0.623575   0.88988674 0.25609267 0.93290424]
 [0.13810718 0.28943217 0.4182005  0.46913886 0.93926716 0.7865521
  0.10096097 0.37386072 0.5458963  0.89973044]], shape=(4, 10), dtype=float32)
- - - - - - - - ds3 - - - - - - - -
(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.19898903, 0.833717  , 0.17857337, 0.19229329], dtype=float32)>, <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[72, 98, 32, 86],
       [80,  9, 44,  6],
       [70, 44, 42, 35],
       [21, 42, 71, 76]])>)


In [52]:
print(ds.element_spec)
print(ds2.element_spec)
print(ds3.element_spec)

TensorSpec(shape=(), dtype=tf.int32, name=None)
TensorSpec(shape=(10,), dtype=tf.float32, name=None)
(TensorSpec(shape=(), dtype=tf.float32, name=None), TensorSpec(shape=(4,), dtype=tf.int32, name=None))


In [55]:
for e in tf.data.Dataset.range(3):
    print(e)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)


In [64]:
inc_ds = tf.data.Dataset.range(100)
inc_ds2 = tf.data.Dataset.range(100, 200)
comb_ds = tf.data.Dataset.zip((inc_ds, inc_ds2))
batch_ds = comb_ds.batch(10)

In [65]:
list(iter(comb_ds))[:3]

[(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
  <tf.Tensor: shape=(), dtype=int64, numpy=100>),
 (<tf.Tensor: shape=(), dtype=int64, numpy=1>,
  <tf.Tensor: shape=(), dtype=int64, numpy=101>),
 (<tf.Tensor: shape=(), dtype=int64, numpy=2>,
  <tf.Tensor: shape=(), dtype=int64, numpy=102>)]

In [82]:
for e in batch_ds: # this continues until all elements 
    print(e) 
    break

(<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)>, <tf.Tensor: shape=(10,), dtype=int64, numpy=array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109], dtype=int64)>)


In [80]:
for e in batch_ds.take(2): # only take(n), n element within ds.
    print(e)

(<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)>, <tf.Tensor: shape=(10,), dtype=int64, numpy=array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109], dtype=int64)>)
(<tf.Tensor: shape=(10,), dtype=int64, numpy=array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64)>, <tf.Tensor: shape=(10,), dtype=int64, numpy=array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119], dtype=int64)>)


In [83]:
"""
Since each element may be different length, especially in sequential models. tf provide Dataset.padded_batch
function
"""
# dataset = tf.data.Dataset.range(100)
# dataset = dataset.map(lambda x: tf.fill([tf.cast(x, tf.int32)], x))
# dataset = dataset.padded_batch(4, padded_shapes=(None,))

# for batch in dataset.take(2):
#     print(batch.numpy())
#     print()

'\nSince each element may be different length, especially in sequential models. tf provide Dataset.padded_batch\nfunction\n'

Petastorm

In [8]:
rel_path = '../datasets/h&m/transaction_train_sample.parquet'

In [18]:
os.path.join('file://', os.getcwd())

'C:\\Users\\haneu\\Desktop\\PROJECTS\\Finance'

In [32]:
'file://' + os.getcwd()

'file://C:\\Users\\haneu\\Desktop\\PROJECTS\\Finance'

In [33]:
os.path.join(os.getcwd(), 'parquet_files')

'C:\\Users\\haneu\\Desktop\\PROJECTS\\Finance\\parquet_files'

In [34]:
os.path.join("file://", os.path.join(os.getcwd(), 'parquet_files'))

'C:\\Users\\haneu\\Desktop\\PROJECTS\\Finance\\parquet_files'

In [56]:
from petastorm import make_reader, make_batch_reader
from petastorm.tf_utils import make_petastorm_dataset

# filepath = 'file://parquet_files'
filepath = os.path.join("file://", os.path.join(os.getcwd(), 'parquet_files'))
filepath = "file:///Users/haneu/Desktop/PROJECTS/Finance/parquet_files"
print(filepath)
with make_reader(dataset_url=filepath) as reader:
    for row in reader:
        print(row)

In [77]:
with make_batch_reader(dataset_url_or_urls=filepath) as reader:
    dataset = make_petastorm_dataset(reader)
#     for row in reader:
#         print(row)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


In [81]:
dataset.element_spec

inferred_schema_view(t_dat=TensorSpec(shape=(None,), dtype=tf.string, name=None), customer_id=TensorSpec(shape=(None,), dtype=tf.string, name=None), article_id=TensorSpec(shape=(None,), dtype=tf.int64, name=None), price=TensorSpec(shape=(None,), dtype=tf.float64, name=None), sales_channel_id=TensorSpec(shape=(None,), dtype=tf.int64, name=None))

In [80]:
type(dataset)

tensorflow.python.data.ops.dataset_ops.DatasetV1Adapter

In [82]:
for e in dataset:
    print(e)

UnknownError: RuntimeError: Trying to read a sample after a reader created by make_reader/make_batch_reader has stopped. This may happen if the make_reader/make_batch_reader context manager has exited but you try to fetch a sample from it anyway
Traceback (most recent call last):

  File "C:\Users\haneu\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\script_ops.py", line 275, in __call__
    ret = func(*args)

  File "C:\Users\haneu\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 649, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\haneu\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 992, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\haneu\AppData\Local\Continuum\anaconda3\lib\site-packages\petastorm\tf_utils.py", line 380, in dequeue_sample_impl
    for row in reader:

  File "C:\Users\haneu\AppData\Local\Continuum\anaconda3\lib\site-packages\petastorm\reader.py", line 690, in __next__
    raise RuntimeError('Trying to read a sample after a reader created by '

RuntimeError: Trying to read a sample after a reader created by make_reader/make_batch_reader has stopped. This may happen if the make_reader/make_batch_reader context manager has exited but you try to fetch a sample from it anyway


	 [[{{node PyFunc}}]] [Op:IteratorGetNext]